import { createHash } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const SOURCE_URL = "https://api-beta.quickfile.co.uk/api-docs/v2";
const EXPECTED_HOST = "api-beta.quickfile.co.uk";
const MINIMUM_PATHS = 40;
const MINIMUM_OPERATIONS = 70;

const response = await fetch(SOURCE_URL, {
  headers: { accept: "application/json" },
  signal: AbortSignal.timeout(30_000),
});

if (!response.ok) {
  throw new Error(`QuickFile Swagger download failed with HTTP ${response.status}`);
}

const document: unknown = await response.json();
assertSwaggerDocument(document);

const canonicalJson = `${JSON.stringify(document, null, 2)}\n`;
const sha256 = createHash("sha256").update(canonicalJson).digest("hex");
const source = [
  "/* eslint-disable */",
  "/**",
  " * Generated by `npm run openapi:sync` from QuickFile's public Swagger v2 document.",
  ` * Source: ${SOURCE_URL}`,
  ` * SHA-256: ${sha256}`,
  " * Do not edit this file by hand.",
  " */",
  'import type { SwaggerDocument } from "../types.js";',
  "",
  `const quickFileOpenApi: SwaggerDocument = ${canonicalJson.trim()};`,
  "",
  "export default quickFileOpenApi;",
  "",
].join("\n");

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const target = resolve(scriptDirectory, "../src/generated/quickfile-openapi.ts");
await mkdir(dirname(target), { recursive: true });
await writeFile(target, source, "utf8");

console.log(
  `Updated ${target} (${Object.keys(document.paths).length} paths, ${countOperations(document.paths)} operations, sha256 ${sha256.slice(0, 12)}…)`,
);

function assertSwaggerDocument(
  value: unknown,
): asserts value is {
  definitions: Record<string, unknown>;
  host: string;
  info: { title: string; version: string };
  paths: Record<string, Record<string, unknown>>;
  schemes: string[];
  swagger: string;
} {
  if (typeof value !== "object" || value === null) {
    throw new Error("QuickFile Swagger response was not a JSON object");
  }

  const candidate = value as Record<string, unknown>;
  if (candidate["swagger"] !== "2.0" || candidate["host"] !== EXPECTED_HOST) {
    throw new Error("Refusing an unexpected Swagger version or API host");
  }

  const paths = candidate["paths"];
  const definitions = candidate["definitions"];
  if (
    typeof paths !== "object" ||
    paths === null ||
    Object.keys(paths).length < MINIMUM_PATHS ||
    countOperations(paths as Record<string, Record<string, unknown>>) <
      MINIMUM_OPERATIONS ||
    typeof definitions !== "object" ||
    definitions === null
  ) {
    throw new Error("QuickFile Swagger document appears incomplete");
  }
}

function countOperations(
  paths: Record<string, Record<string, unknown>>,
): number {
  return Object.values(paths).reduce(
    (total, path) =>
      total +
      Object.keys(path).filter((method) =>
        ["delete", "get", "post", "put"].includes(method),
      ).length,
    0,
  );
}
